export default {
  Add: require('../assets/images/add.png'),
  Home: require('../assets/images/home.png'),
  Heart: require('../assets/images/heart.png'),
  Search: require('../assets/images/search.png'),
  User: require('../assets/images/user.png'),
  SmartPhone: require('../assets/images/smartphone.png'),
  House: require('../assets/images/house.png'),
  Laptop: require('../assets/images/laptop.png'),
  Car: require('../assets/images/car.png'),
  Bikes: require('../assets/images/bike.png'),
  Furniture: require('../assets/images/household.png'),
  NoImage: require('../assets/images/noImage.png'),
  PlaceHolder: require('../assets/images/PlaceHolder.jpeg'),
  Wallet: require('../assets/images/wallet.png'),
  Bell: require('../assets/images/bell.png'),
  Help: require('../assets/images/help.png'),
  Setting: require('../assets/images/setting.png'),
  Blog: require('../assets/images/blog.png'),
  ProfilePicture: require('../assets/images/asta.jpg'),
};
